#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -gt 10 ]
then
        echo "FACTORY RESET" > /dev/console
        jffs2reset -y && reboot &
elif [ "$SEEN" -gt 1 ]
then
        echo "REBOOT" > /dev/console
        sync
        reboot
fi

return 0